MERGE INTO $$target_table_name AS target USING (
  SELECT
    *
  FROM
    (
      select
        *,
        row_number() over (
          partition by $$bronze_temp_table_name.NDC_NUM
          order by
            substr(
              $$bronze_temp_table_name.INPUT_FILE_NAME,
              instr($$bronze_temp_table_name.INPUT_FILE_NAME, 'day=') + 4,
              10
            ) desc,
            substr(
              $$bronze_temp_table_name.INPUT_FILE_NAME,
              instr($$bronze_temp_table_name.INPUT_FILE_NAME, 'hr=') + 3,
              2
            ) desc
        ) as rn
      FROM
        $$bronze_temp_table_name
    )
  WHERE
    rn = 1
) AS source ON target.NDC_NUM = source.NDC_NUM
WHEN MATCHED THEN
UPDATE
SET
  target.GNRC_NAME = source.GNRC_NAM,
  target.PREV_NDC_NUM = source.PREV_NDC_NUM,
  target.OBSOLETE_DT = source.OBSOLETE_DT,
  target.DOSE_FRM_DSCRPTN = source.DOSE_FORM_DSCR,
  target.DRG_STRNTH_DSCRPTN = source.DRG_STRNTH_DSCR,
  target.GNRC_NDCTR = source.GNRC_IND,
  target.GNRC_CD_NUM = source.GNRC_CD_NUM,
  target.THRPUTC_CLASS_CD = source.THERA_CLS_CD,
  target.SPECIF_THRPUTC_CLASS_CD = source.SPECIFIC_THERA_CLS_CD,
  target.PKG_SZ = source.PKG_SIZ,
  target.DRG_FRM_CD = source.DRG_FORM_CD,
  target.ADMIN_RTE_CD = source.ADMIN_RTE_CD,
  target.GNRC_CD_NUM_SEQ = source.GNRC_CD_NUM_SEQ,
  target.REPL_NDC_NUM = source.REPL_NDC_NUM,
  target.DEA_CD = source.DEA_CD,
  target.ADTL_DSCRPTN = source.ADTL_DSCR,
  target.BRND_NAME = source.BRND_NAM,
  target.GNRC_PRC_NDCTR = source.GNRC_PRC_IND,
  target.LBL_NAM = source.LBL_NAM,
  target.MFR_NAM = source.MFR_NAM,
  target.NDC_CNFG_NDCTR = source.NDC_CNFG_IND,
  target.PKG_DSCRPTN = source.PKG_DSCR,
  target.RTE_DSCRTN = source.RTE_DSCR,
  target.TOP_200_NDCTR = source.TOP_200_IND,
  target.UNIT_DOSE_NDCTR = source.UNIT_DOSE_IND,
  target.FFP_UL_CURR_EFFECTIVE_DT = source.FFP_UL_CUR_EFF_DT,
  target.FFP_UL_CURR_UNIT_PRC = source.FFP_UL_CUR_UNIT_PRC,
  target.GNRC_THRPUTC_CLASS_CD = source.GNRC_THERA_CLS_CD,
  target.STNDRD_THRPUTC_CLASS_CD = source.STD_THERA_CLS_CD,
  target.DRG_CLASS_CD = source.DRG_CLS_CD,
  target.INGR_CD_NUM = source.INGR_CD_NUM,
  target.ORANGE_BK_CD = source.ORANGE_BOOK_CD,
  target.CURR_BLU_BK_EFFECTIVE_DT = source.CUR_BLU_BOOK_EFF_DT,
  target.CURR_BLU_BK_UNIT_PRC = source.CUR_BLU_BOOK_UNIT_PRC,
  target.CURR_BLU_BK_PKG_DT = source.CUR_BLU_BOOK_PKG_DT,
  target.CURR_BLU_BK_PKG_PRC = source.CUR_BLU_BOOK_PKG_PRC,
  target.LBLR_ID = source.LBLR_ID,
  target.PATENT_EXPIRATION_DT = source.PATENT_EXPIR_DT,
  target.EXCLSVTY_EXPIRATION_DT = source.EXCLUSIVITY_EXPIR_DT,
  target.DRG_STRNTH_NUM = source.DRG_STRNTH_NUM,
  target.SHLF_PACK_NUM = source.SHLF_PACK_NUM,
  target.PTNT_PKG_INSERT_NDCTR = source.PATIENT_PKG_ISRT_IND,
  target.DISPENSE_CNT = source.DSPNS_CNT,
  target.UPD_DT = source.UPDT_DTS,
  target.CRTE_DT = source.CRTE_DTS,
  target._rescued_data = source._rescued_data,
  target.RECORD_LOAD_TIME = current_timestamp(),
  target.ADF_RUN_ID = source.ADF_RUN_ID,
  target.ADF_JOB_ID = source.ADF_JOB_ID,
  target.DATABRICKS_RUN_ID = '$$DATABRICKS_RUN_ID',
  target.DATABRICKS_JOB_ID = '$$DATABRICKS_JOB_ID',
  target.INPUT_FILE_NAME = source.INPUT_FILE_NAME,
  target.INTEGRATION_KEY = source.INTEGRATION_KEY,
  target.UPDATE_TS = current_timestamp(),
  target.DATE_PART = DATE(current_timestamp()),
  target.HOUR_PART = HOUR(current_timestamp())
WHEN NOT MATCHED BY target THEN
INSERT(
    NDC_NUM,
    GNRC_NAME,
    PREV_NDC_NUM,
    OBSOLETE_DT,
    DOSE_FRM_DSCRPTN,
    DRG_STRNTH_DSCRPTN,
    GNRC_NDCTR,
    GNRC_CD_NUM,
    THRPUTC_CLASS_CD,
    SPECIF_THRPUTC_CLASS_CD,
    PKG_SZ,
    DRG_FRM_CD,
    ADMIN_RTE_CD,
    GNRC_CD_NUM_SEQ,
    REPL_NDC_NUM,
    DEA_CD,
    ADTL_DSCRPTN,
    BRND_NAME,
    GNRC_PRC_NDCTR,
    LBL_NAM,
    MFR_NAM,
    NDC_CNFG_NDCTR,
    PKG_DSCRPTN,
    RTE_DSCRTN,
    TOP_200_NDCTR,
    UNIT_DOSE_NDCTR,
    FFP_UL_CURR_EFFECTIVE_DT,
    FFP_UL_CURR_UNIT_PRC,
    GNRC_THRPUTC_CLASS_CD,
    STNDRD_THRPUTC_CLASS_CD,
    DRG_CLASS_CD,
    INGR_CD_NUM,
    ORANGE_BK_CD,
    CURR_BLU_BK_EFFECTIVE_DT,
    CURR_BLU_BK_UNIT_PRC,
    CURR_BLU_BK_PKG_DT,
    CURR_BLU_BK_PKG_PRC,
    LBLR_ID,
    PATENT_EXPIRATION_DT,
    EXCLSVTY_EXPIRATION_DT,
    DRG_STRNTH_NUM,
    SHLF_PACK_NUM,
    PTNT_PKG_INSERT_NDCTR,
    DISPENSE_CNT,
    UPD_DT,
    CRTE_DT,
    _rescued_data,
    RECORD_LOAD_TIME,
    ADF_RUN_ID,
    ADF_JOB_ID,
    DATABRICKS_RUN_ID,
    DATABRICKS_JOB_ID,
    INPUT_FILE_NAME,
    INTEGRATION_KEY,
    INSERT_TS,
    UPDATE_TS
  )
VALUES
  (
    source.NDC_NUM,
    source.GNRC_NAM,
    source.PREV_NDC_NUM,
    source.OBSOLETE_DT,
    source.DOSE_FORM_DSCR,
    source.DRG_STRNTH_DSCR,
    source.GNRC_IND,
    source.GNRC_CD_NUM,
    source.THERA_CLS_CD,
    source.SPECIFIC_THERA_CLS_CD,
    source.PKG_SIZ,
    source.DRG_FORM_CD,
    source.ADMIN_RTE_CD,
    source.GNRC_CD_NUM_SEQ,
    source.REPL_NDC_NUM,
    source.DEA_CD,
    source.ADTL_DSCR,
    source.BRND_NAM,
    source.GNRC_PRC_IND,
    source.LBL_NAM,
    source.MFR_NAM,
    source.NDC_CNFG_IND,
    source.PKG_DSCR,
    source.RTE_DSCR,
    source.TOP_200_IND,
    source.UNIT_DOSE_IND,
    source.FFP_UL_CUR_EFF_DT,
    source.FFP_UL_CUR_UNIT_PRC,
    source.GNRC_THERA_CLS_CD,
    source.STD_THERA_CLS_CD,
    source.DRG_CLS_CD,
    source.INGR_CD_NUM,
    source.ORANGE_BOOK_CD,
    source.CUR_BLU_BOOK_EFF_DT,
    source.CUR_BLU_BOOK_UNIT_PRC,
    source.CUR_BLU_BOOK_PKG_DT,
    source.CUR_BLU_BOOK_PKG_PRC,
    source.LBLR_ID,
    source.PATENT_EXPIR_DT,
    source.EXCLUSIVITY_EXPIR_DT,
    source.DRG_STRNTH_NUM,
    source.SHLF_PACK_NUM,
    source.PATIENT_PKG_ISRT_IND,
    source.DSPNS_CNT,
    source.UPDT_DTS,
    source.CRTE_DTS,
    source._rescued_data,
    current_timestamp(),
    source.ADF_RUN_ID,
    source.ADF_JOB_ID,
    '$$DATABRICKS_RUN_ID',
    '$$DATABRICKS_JOB_ID',
    source.INPUT_FILE_NAME,
    source.INTEGRATION_KEY,
    current_timestamp(),
    current_timestamp()
  )