-- Databricks notebook source
CREATE OR REPLACE VIEW edp_psas_di_dev.edp_psas_di_usp_gold.vw_mpb_rep_prod_lkg_dtl AS
SELECT
    BUSINESS_UNIT,
    SEGMENT,
    UPPER(COALESCE(SLS_REP, '')) AS SALES_REP,
    UPPER(COALESCE(PROD_NAME, '')) AS BRAND,
    UPPER(COALESCE(MNC_PROD_ACCESS, '') )AS PRODUCT_ACCESS,
    COALESCE(LKG_RANK, 0) AS LEAKAGE_RANK,
    UPPER(COALESCE(PROD_ACCESS_CTGRY, '')) AS PRODUCT_ACCESS_CATEGORY,
    COALESCE(YR_MTH, '') AS YEAR_MONTH,
    COALESCE(LKG_RANK_WGHT, 0) AS LEAKAGE_RANK_WEIGHT,
    RECORD_LOAD_TIME,
    DATABRICKS_RUN_ID,
    DATABRICKS_JOB_ID,
    INSERT_TS,
    UPDATE_TS
FROM
    EDP_PSAS_DI_DEV.EDP_PSAS_DI_USP_GOLD.t_mpb_rep_prod_lkg_dtl;
