-- Databricks notebook source
CREATE OR REPLACE VIEW edp_psas_di_dev.edp_psas_di_usp_gold.vw_mpb_cust_prod_access_dtl AS
SELECT
    BUSINESS_UNIT,
    SEGMENT,
    CONCAT(LTRIM('0', COALESCE(CUST_ACCT_ID, '')), ' ', UPPER(COALESCE(CUST_ACCT_NAME, ''))) AS CUSTOMER,
    UPPER(COALESCE(PROD_NAME, '')) AS BRAND,
    UPPER(COALESCE(MNC_PROD_ACCESS, '')) AS PRODUCT_ACCESS,
    CONCAT(LTRIM('0', COALESCE(CMMN_GRP_ID, '')), ' ', UPPER(COALESCE(CMMN_GRP_NAME, ''))) AS COMMON_GROUP,
    CONCAT(LTRIM('0', COALESCE(CMMN_ENTITY_ID, '')), ' ', UPPER(COALESCE(CMMN_ENTITY_NAME, ''))) AS COMMON_ENTITY,
    CONCAT(LTRIM('0', COALESCE(CHN_ID, '')), ' ', UPPER(COALESCE(CHN_NAME, ''))) AS CHAIN,
    CONCAT(LTRIM('0', COALESCE(NATL_GRP_CD, '')), ' ', UPPER(COALESCE(NATL_GRP_NAME, ''))) AS NATIONAL_GROUP,
    CONCAT(LTRIM('0', COALESCE(NATL_SUB_GRP_CD, '')), ' ', UPPER(COALESCE(NATL_SUB_GRP_NAME, ''))) AS NATIONAL_SUB_GROUP,
    CONCAT(LTRIM('0', COALESCE(ACCT_CLASS_CD, '')), ' ', UPPER(COALESCE(ACCT_CLASS_DESC, ''))) AS ACCOUNT_CLASSIFICATION,
    CONCAT(LTRIM('0', COALESCE(COT_KEY, '')), ' ', UPPER(COALESCE(COT_DESC, ''))) AS CLASS_OF_TRADE,
    COALESCE(DEA_NUM, '') AS DEA_NUMBER,
    CONCAT(LTRIM('0', COALESCE(CUST_REGION_NUM, '')), ' ', UPPER(COALESCE(CUST_REGION_NAME, ''))) AS REGION,
    UPPER(COALESCE(STATE, '')) AS STATE,
    UPPER(COALESCE(CUST_PROD_ACCESS_INDICATOR, '')) AS CUSTOMER_PRODUCT_ACCESS_INDICATOR,
    UPPER(COALESCE(CMMN_ENTITY_PROD_ACCESS_INDICATOR, '')) AS COMMON_ENTITY_PRODUCT_ACCESS_INDICATOR,
    LKG_FLG AS LEAKAGE_FLAG,
    UPPER(COALESCE(PROD_ACCESS_CTGRY, '')) AS PRODUCT_ACCESS_CATEGORY,
    UPPER(COALESCE(THRPUTC_CLASS, '')) AS THERAPUTIC_CLASS,
    RECORD_LOAD_TIME,
    DATABRICKS_RUN_ID,
    DATABRICKS_JOB_ID,
    INSERT_TS,
    UPDATE_TS
FROM
    EDP_PSAS_DI_DEV.EDP_PSAS_DI_USP_GOLD.T_MPB_CUST_PROD_ACCESS_DTL;
