name: Deploy Linked Service to ADF

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment'
        type: string
        required: true
      function_name:
        description: 'Data source'
        type: string
        required: true
      date:
        description: 'Commit date'
        type: string
        required: true

jobs:
  deploy-linked-service:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Log in to Azure using the service principal credentials stored in AZURE_CREDENTIALS
    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    # Deploy Linked Service using Azure CLI
    - name: Deploy Linked Service to ADF
      env:
        AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
        RESOURCE_GROUP: ${{ secrets.AZURE_RESOURCE_GROUP }}
        DATA_FACTORY_NAME: ${{ secrets.ADF_NAME }}
        ENVIRONMENT: ${{ github.event.inputs.environment }}
        FUNCTION_NAME: ${{ github.event.inputs.function_name }}
        DATE: ${{ github.event.inputs.date }}
      run: |
        echo "Deploying Linked Service for environment: $ENVIRONMENT, function: $FUNCTION_NAME, date: $DATE"
        
        # Set Azure subscription context
        az account set --subscription $AZURE_SUBSCRIPTION_ID
        
        # Assuming you use the function_name to reference different linked service JSON files
        LINKED_SERVICE_JSON="linked-services/$FUNCTION_NAME-$DATE.json"

        # Deploy Linked Service
        az datafactory linked-service create \
          --factory-name $DATA_FACTORY_NAME \
          --resource-group $RESOURCE_GROUP \
          --name $FUNCTION_NAME \
          --properties @$LINKED_SERVICE_JSON
