name: Publish ADF Pipelines

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: choice
        options:
          - dev
          - qa
          - prod
        required: true
      function_name:
        description: "Enter the data source to deploy (e.g., MPB-MNC, SA_INSIGHTS)"
        type: string
        required: true
      adf_pipelines_deployment_steps:
        description: 'Select ADF Pipelines deployment step'
        type: choice
        options:
          - none
          - all
          - landing
          - bronze
          - silver
          - gold
          - master
          - miscellaneous
        required: false
        default: 'none'
      date:
        description: 'Deploy changes after a commit date in YYYY-MM-DD format (OPTIONAL)'
        type: string
        default: '1999-01-01'
        required: true

env:
  ENVIRONMENT: ${{ inputs.environment }}
  DATE: ${{ inputs.date }}
  FUNCTION_NAME: ${{ inputs.function_name }}
  BRANCH: ${{ github.ref_name }}

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref_name }}

      - name: Install Azure CLI
        run: |
          curl -sL https://aka.ms/InstallAzureCLIDeb | sudo bash

      - name: Get changed files since provided date
        id: changed-files-since
        uses: tj-actions/changed-files@v37
        with:
          since: "${{ env.DATE }}"
          files: "dataproducts/${{ env.FUNCTION_NAME }}/pipelines/"

      - name: Publish ADF Pipelines
        run: |
          if [[ $ENVIRONMENT == 'dev' ]]; then
            az login --service-principal --username "${{ secrets.CLIENT }}" --password "${{ secrets.CLIENTSECRET }}" --tenant "${{ secrets.TENANT }}"
            az account set -s ${{ secrets.SUBSCRIPTION_ID }}
            FACTORY_NAME="adf-psasdi-westus-dev-01"
            RESOURCE_GROUP="rg-psas-decision-intelligence-westus-dev"
          elif [[ $ENVIRONMENT == 'qa' ]]; then
            az login --service-principal --username "${{ secrets.CLIENT_ID_QAT }}" --password "${{ secrets.CLIENT_SECRET_QAT }}" --tenant "${{ secrets.TENANT_ID_QAT }}"
            az account set -s ${{ secrets.SUBSCRIPTION_ID_QAT }}
            FACTORY_NAME="${{ secrets.FACTORY_NAME_QAT }}"
            RESOURCE_GROUP="${{ secrets.RESOURCE_GROUP_QAT }}"
          elif [[ $ENVIRONMENT == 'prod' ]]; then
            az login --service-principal --username "${{ secrets.CLIENT_ID_PROD }}" --password "${{ secrets.CLIENT_SECRET_PROD }}" --tenant "${{ secrets.TENANT_ID_PROD }}"
            az account set -s ${{ secrets.SUBSCRIPTION_ID_PROD }}
            FACTORY_NAME="${{ secrets.FACTORY_NAME_PROD }}"
            RESOURCE_GROUP="${{ secrets.RESOURCE_GROUP_PROD }}"
          fi

          echo "Logged in successfully"

          # Check if 'all' is selected and deploy pipelines accordingly
          if [[ $adf_pipelines_deployment_steps == "all" ]]; then
            for file in ${{ steps.changed-files-since.outputs.all_changed_files }}; do
              if [[ $file == dataproducts/${{ env.FUNCTION_NAME }}/pipelines/* && $file == *".json" ]]; then
                echo "Deploying pipeline with change after the date: $file"
                pipeline_name=${file##*/} 
                pipeline_name=${pipeline_name%.*}  # Remove the file extension

                # Deploy the pipeline to a specific folder
                folder_name="test_folder"  # Specify your folder here
                az datafactory pipeline create --factory-name $FACTORY_NAME --pipeline $file --name $pipeline_name --resource-group $RESOURCE_GROUP --folder "$folder_name"
              fi
            done
          else
            folder="dataproducts/${{ env.FUNCTION_NAME }}/pipelines/${{ env.adf_pipelines_deployment_steps }}/"
            for file in ${{ steps.changed-files-since.outputs.all_changed_files }}; do
              if [[ $file == $folder* && $file == *".json" ]]; then
                echo "Deploying pipeline from $adf_pipelines_deployment_steps folder: $file"
                pipeline_name=${file##*/} 
                pipeline_name=${pipeline_name%.*}  # Remove the file extension

                # Deploy the pipeline to a specific folder
                folder_name="test_folder"  # Specify your folder here
                az datafactory pipeline create --factory-name $FACTORY_NAME --pipeline $file --name $pipeline_name --resource-group $RESOURCE_GROUP --folder "$folder_name"
              fi
            done
          fi
