name: Databricks Deployment

on:
  workflow_call:
    inputs:
      environment:
        type: string
        required: true
      date:
        type: string
        required: true
      databricks_deployment_steps:
        type: string
        required: true

env:
  ENVIRONMENT: ${{ inputs.environment }}
  DATE: ${{ inputs.date }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Get changed files since
        id: changed-files-since
        uses: tj-actions/changed-files@v37
        with:
          since: "${{ env.DATE }}"
          files: "common_utilities/"

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Setup Databricks environment
        run: |
          if [ "${{ inputs.environment }}" == 'dev' ]; then 
            export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_DEV }}
            export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_DEV }}
          elif [ "${{ inputs.environment }}" == 'qat' ]; then
            export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_QAT }}
            export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_QAT }}
          elif [ "${{ inputs.environment }}" == 'prod' ]; then
            export DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST_PROD }}
            export DATABRICKS_TOKEN=${{ secrets.DATABRICKS_TOKEN_PROD }}
          fi

      - name: Deploy Databricks Files
        run: |
          echo "Deploying to Databricks for environment: ${{ inputs.environment }} after date: ${{ inputs.date }}"
          
          # Logic for deploying Databricks files based on deployment step input
          if [[ "${{ inputs.databricks_deployment_steps }}" == "ingestion_utilities" ]]; then
            echo "Deploying Ingestion Utilities..."
            databricks workspace import_dir common_utilities/ /Shared/sandbox/ --overwrite
          fi
          
          if [[ "${{ inputs.databricks_deployment_steps }}" == "ddl" ]]; then
            echo "Deploying DDL files..."
            databricks workspace import_dir ddl/ /Shared/sandbox/ddl_dml/ --overwrite
          fi
          
          if [[ "${{ inputs.databricks_deployment_steps }}" == "dml" ]]; then
            echo "Deploying DML files..."
            databricks workspace import_dir dml/ /Shared/sandbox/ddl_dml/ --overwrite
          fi
          
          if [[ "${{ inputs.databricks_deployment_steps }}" == "all" ]]; then
            echo "Deploying all selected Databricks files..."
            # Deploy Ingestion Utilities
            databricks workspace import_dir common_utilities/ /Shared/sandbox/ --overwrite
            # Deploy DDL files
            databricks workspace import_dir ddl/ /Shared/sandbox/ddl_dml/ --overwrite
            # Deploy DML files
            databricks workspace import_dir dml/ /Shared/sandbox/ddl_dml/ --overwrite
          fi

      - name: Clean up temporary directories
        run: |
          echo "Cleaning up temporary directories..."
          rm -rf /tmp/cu/py/
          rm -rf /tmp/cu/ddl_dml/
