name: Master Deployment Workflow_testing

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to deploy (e.g., main, dev, qa)'
        type: string
        required: true
        default: ''
      environment_source:
        description: 'Combined environment and source (e.g., "dev:MPB-MNC")'
        type: string
        required: true
        default: 'dev:MPB-MNC'
      date:
        description: 'Deploy changes after a commit date (YYYY-MM-DD)'
        type: string
        default: '1999-01-01'
        required: true
      databricks_deployment_steps:
        description: 'Select Databricks deployment step'
        type: choice
        options:
          - none
          - ddl
          - dml
          - all
        required: false
        default: 'none'
      adf_pipelines_deployment_steps:
        description: 'Select ADF Pipelines deployment step'
        type: choice
        options:
          - none
          - all
          - landing
          - bronze
          - silver
          - gold
          - master
          - miscellaneous
        required: false
        default: 'none'
      deploy_linked_service:
        description: 'Deploy ADF Linked Services'
        type: boolean
        required: false
      deploy_datasets:
        description: 'Deploy ADF Datasets'
        type: boolean
        required: false
      deploy_triggers:
        description: 'Deploy ADF Triggers'
        type: boolean
        required: false
      deploy_dataflows:
        description: 'Deploy ADF Dataflows'
        type: boolean
        required: false

env:
  DATE: ${{ inputs.date }}
  BRANCH: ${{ inputs.branch }}

jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Split Environment and Source
        run: |
          ENVIRONMENT=$(echo "${{ inputs.environment_source }}" | cut -d':' -f1)
          SOURCE=$(echo "${{ inputs.environment_source }}" | cut -d':' -f2)
          echo "Environment: $ENVIRONMENT"
          echo "Source: $SOURCE"
          
          # Validate environment and source
          if [[ -z "$ENVIRONMENT" || -z "$SOURCE" ]]; then
            echo "Both environment and source must be provided."
            exit 1
          fi

      - name: Validate Date Format
        run: |
          if ! [[ "${{ inputs.date }}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            echo "Invalid date format. Use YYYY-MM-DD."
            exit 1
          fi

      - name: Validate Future Date
        run: |
          if [[ "${{ inputs.date }}" > "$(date +%Y-%m-%d)" ]]; then
            echo "The specified date is in the future. Provide a valid past date."
            exit 1
          fi

      - name: Validate Deployment Inputs
        run: |
          if [[ "${{ inputs.deploy_linked_service }}" == "true" || "${{ inputs.deploy_datasets }}" == "true" || "${{ inputs.deploy_dataflows }}" == "true" ]]; then
            if [[ "$SOURCE" == "none" ]]; then
              echo "If deploying linked services, datasets, or dataflows, a valid function name (source) must be provided."
              exit 1
            fi
          fi

  trigger_workflows:
    needs: validate_inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Split Environment and Source
        run: |
          ENVIRONMENT=$(echo "${{ inputs.environment_source }}" | cut -d':' -f1)
          SOURCE=$(echo "${{ inputs.environment_source }}" | cut -d':' -f2)
          echo "Environment: $ENVIRONMENT"
          echo "Source: $SOURCE"

      # Trigger Databricks Deployment
      - name: Trigger Databricks Deployment
        if: ${{ inputs.databricks_deployment_steps != 'none' }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "$ENVIRONMENT", "date": "${{ inputs.date }}", "databricks_deployment_steps": "${{ inputs.databricks_deployment_steps }}", "function_name": "$SOURCE"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/databricks.yml/dispatches

      # Trigger ADF Pipelines Deployment
      - name: Trigger ADF Pipelines Deployment
        if: ${{ inputs.adf_pipelines_deployment_steps != 'none' }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "$ENVIRONMENT", "date": "${{ inputs.date }}", "adf_pipelines_deployment_steps": "${{ inputs.adf_pipelines_deployment_steps }}", "function_name": "$SOURCE"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_pipelines.yml/dispatches

      # Trigger ADF Linked Services Deployment
      - name: Trigger ADF Linked Services Deployment
        if: ${{ inputs.deploy_linked_service == true }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "$ENVIRONMENT", "date": "${{ inputs.date }}", "function_name": "$SOURCE"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_linked_service.yml/dispatches

      # Trigger ADF Datasets Deployment
      - name: Trigger ADF Datasets Deployment
        if: ${{ inputs.deploy_datasets == true }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "$ENVIRONMENT", "date": "${{ inputs.date }}", "function_name": "$SOURCE"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_dataset.yml/dispatches

      # Trigger ADF Triggers Deployment
      - name: Trigger ADF Triggers Deployment
        if: ${{ inputs.deploy_triggers == true }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "$ENVIRONMENT", "date": "${{ inputs.date }}", "function_name": "$SOURCE"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_trigger.yml/dispatches

      # Trigger ADF Dataflows Deployment
      - name: Trigger ADF Dataflows Deployment
        if: ${{ inputs.deploy_dataflows == true }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "$ENVIRONMENT", "date": "${{ inputs.date }}", "function_name": "$SOURCE"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/adf_dataflows.yml/dispatches
