name: Master Deployment Workflow_3

on:
  workflow_dispatch:
    inputs:
      branch:
        description: 'Select the branch to deploy (e.g., main, dev, qa)'
        type: string
        required: true
        default: 'main'
      environment_source:
        description: 'Combined environment and source (e.g., "dev:MPB-MNC")'
        type: string
        required: true
        default: 'dev:MPB-MNC'
      date:
        description: 'Deploy changes after a commit date (YYYY-MM-DD)'
        type: string
        required: true
        default: '1999-01-01'
      databricks_deployment_steps:
        description: 'Select Databricks deployment step'
        type: choice
        options:
          - none
          - ddl
          - dml
          - all
        required: false
        default: 'none'
      adf_pipelines_deployment_steps:
        description: 'Select ADF Pipelines deployment step'
        type: choice
        options:
          - none
          - all
          - landing
          - bronze
          - silver
          - gold
          - master
          - miscellaneous
        required: false
        default: 'none'
      deploy_linked_service:
        description: 'Deploy ADF Linked Services'
        type: boolean
        required: false
      deploy_datasets:
        description: 'Deploy ADF Datasets'
        type: boolean
        required: false
      deploy_triggers:
        description: 'Deploy ADF Triggers'
        type: boolean
        required: false
      deploy_dataflows:
        description: 'Deploy ADF Dataflows'
        type: boolean
        required: false

env:
  DATE: ${{ inputs.date }}
  BRANCH: ${{ inputs.branch }}

jobs:
  validate_inputs:
    runs-on: ubuntu-latest
    steps:
      - name: Split Environment and Source
        run: |
          # Split environment_source into ENVIRONMENT and FUNCTION_NAME
          ENVIRONMENT=$(echo "${{ inputs.environment_source }}" | cut -d':' -f1)
          FUNCTION_NAME=$(echo "${{ inputs.environment_source }}" | cut -d':' -f2)
          
          echo "ENVIRONMENT: $ENVIRONMENT"
          echo "FUNCTION_NAME: $FUNCTION_NAME"
          
          # Set the split values as environment variables
          echo "ENVIRONMENT=$ENVIRONMENT" >> $GITHUB_ENV
          echo "FUNCTION_NAME=$FUNCTION_NAME" >> $GITHUB_ENV

      - name: Validate Date Format
        run: |
          if ! [[ "${{ inputs.date }}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            echo "Invalid date format. Use YYYY-MM-DD."
            exit 1
          fi

      - name: Validate Future Date
        run: |
          if [[ "${{ inputs.date }}" > "$(date +%Y-%m-%d)" ]]; then
            echo "The specified date is in the future. Provide a valid past date."
            exit 1
          fi

  trigger_workflows:
    needs: validate_inputs
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ inputs.branch }}

      - name: Trigger Databricks Deployment
        if: ${{ inputs.databricks_deployment_steps != 'none' }}
        run: |
          curl -X POST \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -d '{"ref": "refs/heads/${{ inputs.branch }}", "inputs": {"environment": "${{ env.ENVIRONMENT }}", "date": "${{ env.DATE }}", "databricks_deployment_steps": "${{ inputs.databricks_deployment_steps }}", "function_name": "${{ env.FUNCTION_NAME }}"}}' \
            https://api.github.com/repos/${{ github.repository }}/actions/workflows/databricks.yml/dispatches

      # Add more triggers for ADF Pipelines, Linked Services, etc. as needed
