name: Master Deployment Workflow

on: 
  workflow_dispatch:
    inputs:
      environment:
        description: 'Environment to deploy'
        type: environment
        required: true
      function_name:
        type: choice
        description: 'Select Data Source to deploy'
        options:
        - none
        - all
        - IQVIA_SALES
        - SAP_FICO
        - SAP_MASTER
        - SFDC_CRM
        - VARICENT_SALES
        required: true
      databricks_deployment:
        description: 'Databricks Deployment'
        type: boolean
        required: false
      deploy_linked_service:
        description: 'Deploy ADF Linked Services'
        type: boolean
        required: false
      deploy_datasets:
        description: 'Deploy ADF Datasets'
        type: boolean
        required: false     
      deploy_common_pipelines:
        description: 'Deploy ADF Common Pipelines'
        type: boolean
        required: false
      deploy_triggers:
        description: 'Deploy ADF Triggers'
        type: boolean
        required: false
      date: 
        description: 'Deploy changes after a commit date in YYYY-MM-DD format (OPTIONAL)'
        type: string
        default: '1999-01-01'
        required: true

env:
  ENVIRONMENT: ${{ inputs.environment }}
  DATE: ${{ inputs.date }}

jobs:
  validate_date:
    runs-on: ubuntu-latest
    steps:
      - name: Validate Date Format
        run: |
          if ! [[ "${{ inputs.date }}" =~ ^[0-9]{4}-[0-9]{2}-[0-9]{2}$ ]]; then
            echo "Invalid date format. Please use YYYY-MM-DD."
            exit 1
          fi

  trigger_workflows_1:
    name: Databricks Deployment
    if: ${{ inputs.databricks_deployment == 'true' }}
    uses: ./.github/workflows/databricks.yml
    with:
      environment: ${{ inputs.environment }}
      date: ${{ inputs.date }}
    secrets: inherit

  trigger_workflows_2:
    name: ADF Dataset Deployment
    if: ${{ inputs.deploy_datasets == 'true' }}
    uses: ./.github/workflows/adf_dataset.yml
    with:
      environment: ${{ inputs.environment }}
      date: ${{ inputs.date }}
    secrets: inherit

  trigger_workflows_3:
    name: ADF Linked Services Deployment
    if: ${{ inputs.deploy_linked_service == 'true' }}
    uses: ./.github/workflows/adf_linked_service.yml
    with:
      environment: ${{ inputs.environment }}
      date: ${{ inputs.date }}
    secrets: inherit

  trigger_workflows_4:
    name: ADF Common Pipelines Deployment
    if: ${{ inputs.deploy_common_pipelines == 'true' }}
    uses: ./.github/workflows/adf_common_pipelines.yml
    with:
      environment: ${{ inputs.environment }}
      date: ${{ inputs.date }}
    secrets: inherit

  trigger_workflows_5:
    name: ADF Triggers Deployment
    if: ${{ inputs.deploy_triggers == 'true' }}
    uses: ./.github/workflows/adf_triggers.yml
    with:
      environment: ${{ inputs.environment }}
      date: ${{ inputs.date }}
    secrets: inherit

  # Deploy functions based on selected data sources
  deploy_selected_functions:
    name: Deploy Selected Data Sources
    if: ${{ inputs.function_name != 'none' && inputs.function_name != 'all' }}
    strategy:
      matrix:
        function: 
          - ${{ inputs.function_name }}
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Data Source
        run: |
          echo "Deploying function: ${{ matrix.function }}"
          # Trigger specific deployments based on the selected function.
          # Add your deployment commands here for each function.
  
  # Deploy all data sources if 'all' is selected
  deploy_all_functions:
    name: Deploy All Data Sources
    if: ${{ inputs.function_name == 'all' }}
    strategy:
      matrix:
        function: 
          - IQVIA_SALES
          - SAP_FICO
          - SAP_MASTER
          - SFDC_CRM
          - VARICENT_SALES
    runs-on: ubuntu-latest
    steps:
      - name: Deploy Data Source
        run: |
          echo "Deploying function: ${{ matrix.function }}"
          # Trigger specific deployments for each function, depending on your implementation.
